Event
LahessAimere/Johanne_2023-2024_Eartsup_Unity pull request #2
Opened 2023-10-17 20:59 UTC by LahessAimere

2023-10-18 11:56 UTC, GuitoonDev requested changes
L'énoncé de l'exercice est respecté tout est bon de ce côté mais il y a trop de petites erreurs pour que ça soit ok à mon sens.

Petit détail :
Je crois qu'il y a un soucis avec l'interface de ta barre de vie
![image](https://github.com/LahessAimere/Johanne_2023-2024_Eartsup_Unity/assets/32094695/6fdcc6d2-b301-49a9-8407-dd494406720d)

2023-10-18 11:56 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +    [SerializeField] private ScriptableEventInt _healthChangedEventInt;
[Ne respecte pas la règle n°3 des conventions d'écriture](https://pastebin.com/ZbTgSgNx)

2023-10-18 11:56 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +    void Start()
Si la fonction est vide alors autant la supprimer du fichier

2023-10-18 11:56 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/ColliderEvent.cs
> +    public void OnTriggerEnter(Collider other)
Aère un peu ton code

2023-10-18 11:56 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/HealthBar.cs
> +    private Image _image;
[Ne respecte pas la règle n°3 des conventions d'écriture](https://pastebin.com/ZbTgSgNx)

2023-10-18 11:56 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/HealthBar.cs
> +      _scriptableEventInt.Event += ChangedHealthBar;
Il y a une inconsistance dans l'indentation des lignes de cette fonction

2023-10-18 11:56 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/ScriptableEventInt.cs
> +[CreateAssetMenu(fileName = "new" + nameof(ScriptableEventInt), menuName = "Events/Scriptable Object")]
ça manque d'un espace après les `using`

2023-10-18 11:56 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/ScriptableEventInt.cs
> +    public void Test()
Si les fonctions sont commentées soient il vaut mieux les supprimer soit elles serviront pour des modifications futures.

2023-10-18 11:56 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical.meta
Il me semble que l'anglais de "Pratique" c'est "Practice" ou "Practical"

2023-10-18 11:56 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +using UnityEngine.Serialization;
Je crois qu'il y a beaucoup plus de `using` que ce dont tu as besoin dans ton script.

2023-10-18 11:56 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/HealthBar.cs
> +using System.Net.Mime;
Fais attention aux `using` inutiles dans ton code !

2023-10-18 11:56 UTC, GuitoonDev commented on Assets/Events/Scripts/Théorical.meta
Attention aux noms de tes fichier/dossiers, si tu mets un accent ça veut dire que tu me fais un mix anglais/français !

Et j'insiste sur ce point :
PAS DE FRANÇAIS DANS LE PROJET/CODE !!!

2023-10-23 15:06 UTC, LahessAimere commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +    void Start()
Ah oui vu que j'avais mis le Start en commentaire je ne savais pas que ça gênait

2023-10-23 16:15 UTC, LahessAimere commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +    [SerializeField] private ScriptableEventInt _healthChangedEventInt;
Est ce ça s'écrit sans le underscore "healthChangedEventInt" ? Parce que je crois du coup que je n'ai pas compris l'utilisation de ce caractère.

2023-10-23 16:21 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +    [SerializeField] private ScriptableEventInt _healthChangedEventInt;
Le problème n'est pas au niveau de du _underscore_ mais au niveau de l'ordre de tes variables par rapport à l'ordre dans lesquelles elles doivent être rangées dans les conventions d'écriture.
```cs
[...]
        // public members
        // protected [SerializedField] members
        // private [SerializedField] members
    
        // inline members
        // protected members
        // private members
[...]
```

2023-10-23 16:53 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +    [SerializeField] private ScriptableEventInt _healthChangedEventInt;
> De plus, Je n'ai pas compris le problème de l'interface de la barre de vie ?

Dans le screen, le cadre blanc c'est ton canvas pour ton ui. C'est ton cadre qui représente les éléments de l'UI qui sont affichés à l'écran.

Ton image est donc bien trop grosse par rapport à ce qui est affiché à l'écran.

2023-10-23 17:27 UTC, LahessAimere commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +    [SerializeField] private ScriptableEventInt _healthChangedEventInt;
Ah d'accord je n'avais pas compris pour l'ordre des variables je vais changé ça !
Par contre la barre de vie, je trouve ça bizarre parce que moi je ne la vois pas du tout comme ça.

![Capture d'écran 2023-10-23 192529](https://github.com/LahessAimere/Johanne_2023-2024_Eartsup_Unity/assets/80914959/f87ab367-61be-4bc3-b8f9-c2925adb9e9d)

2023-10-25 12:52 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +    [SerializeField] private ScriptableEventInt _healthChangedEventInt;
Est-ce que tu es en "Free Aspect" sur ta fenêtre "Game" ?
Il me semble que ça peut venir de là.
Perso, je mets toujours "16:9 Aspect" pour avoir un affichage cohérent avec les écrans rééls.

2023-10-25 12:59 UTC, GuitoonDev requested changes
La vie baisse quand j'appuie sur Espace mais elle ne baisse plus quand je déplace le Character dans le cube.

2023-10-25 12:59 UTC, GuitoonDev commented on Assets/Events/Scripts/Practical/CharacterBehavior.cs
> +
Ligne superflue

2023-10-25 12:59 UTC, GuitoonDev commented on Assets/Events/Scripts/Practical/ColliderEvent.cs
> +    [SerializeField] private UnityEvent unityEvent;
Ta variable privée ne commence pas par un underscore.

2023-10-25 12:59 UTC, GuitoonDev commented on Assets/Events/Scripts/Practical/HealthBar.cs
> +    [SerializeField] private ScriptableEventInt scriptableEventInt;
Ta variable privée ne commence pas par un underscore.

2023-10-26 13:36 UTC, LahessAimere commented on Assets/Events/Scripts/Practical/CharacterBehavior.cs
> +    [SerializeField] private ScriptableEventInt healthChangedEventInt;
Ah oui je dois tout rechanger parce que je pensais que l'erreur était là la dernière fois

2023-10-26 13:58 UTC, LahessAimere commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +    [SerializeField] private ScriptableEventInt _healthChangedEventInt;
Ah oui d'accord, je vais changer ça et j'ai une question par rapport au texte, parce que j'ai voulue rajouté un "health" au dessus avec un text mesh pro, mais je voulais savoir si il y avait une astuce pour que la qualité du texte soit mieux que ça :
![image](https://github.com/LahessAimere/Johanne_2023-2024_Eartsup_Unity/assets/80914959/cb32f5ef-1fb1-409e-bf76-2203fadb5c73)

2023-10-26 14:45 UTC, GuitoonDev commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +    [SerializeField] private ScriptableEventInt _healthChangedEventInt;
On reparlera de ça quand on parlera des UI je pense

2023-10-26 14:47 UTC, LahessAimere commented on Assets/Events/Scripts/Pratical/CharacterBehavior.cs
> +    [SerializeField] private ScriptableEventInt _healthChangedEventInt;
D'accord

2023-12-20 10:46 UTC, closed without merging